[env]
TERM = "xterm-256color"

[keyboard]
bindings = [ { key = "F11", action = "ToggleFullScreen" } ]

[font]
size = 15.5
normal = { family = "IosevkaNerdFontMono", style = "Regular" }
bold = { family = "IosevkaNerdFontMono", style = "Bold" }
italic = { family = "IosevkaNerdFontMono", style = "Italic" }
bold_italic = { family = "IosevkaNerdFontMono", style = "Italic" } # BoldItalic doesnt work?

[mouse]
hide_when_typing = true

[window]
position = { x = 320, y = 120 }
dimensions = { columns = 210, lines = 46 }
padding = { x = 5, y = 0 }

[cursor]
style = { blinking = "Always" }

[colors.primary]
background = "#22272e"
foreground = "#adbac7"

[colors.cursor]
text = "#22272e"
cursor = "#adbac7"

[colors.normal]
black = "#545d68"
red = "#f47067"
green = "#57ab5a"
yellow = "#c69026"
blue = "#539bf5"
magenta = "#b083f0"
cyan = "#39c5cf"
white = "#909dab"

[colors.bright]
black = "#636e7b"
red = "#ff938a"
green = "#6bc46d"
yellow = "#daaa3f"
blue = "#6cb6ff"
magenta = "#b083f0"
cyan = "#39c5cf"
white = "#909dab"
