[env]
TERM = "xterm-256color"

[keyboard]
bindings = [ { key = "F11", action = "ToggleFullScreen" } ]

[font]
size = 15.5
normal = { family = "IosevkaNerdFontMono", style = "Regular" }
bold = { family = "IosevkaNerdFontMono", style = "Bold" }
italic = { family = "IosevkaNerdFontMono", style = "Italic" }
bold_italic = { family = "IosevkaNerdFontMono", style = "Italic" } # BoldItalic doesnt work?

[mouse]
hide_when_typing = true

[window]
position = { x = 320, y = 120 }
dimensions = { columns = 210, lines = 46 }
padding = { x = 5, y = 0 }

[cursor]
style = { blinking = "Always" }

[colors.primary]
background = '#282c34'
foreground = '#bbc2cf'

[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#c678dd'
cyan    = '#46d9ff'
white   = '#bbc2cf'

[colors.bright]
black   = '#53565c'
red     = '#ff8988'
green   = '#accb83'
yellow  = '#efcb95'
blue    = '#73bff2'
magenta = '#d193e3'
cyan    = '#6be0ff'
white   = '#c8ced8'
