#!/usr/bin/env bash

if [[ "$XDG_CURRENT_DESKTOP" == *i3* || "$DESKTOP_SESSION" == "i3" ]]; then
  fullscreen_mode=$(i3-msg -t get_tree | jq 'recurse(.nodes[] + .floating_nodes[]; .nodes != null)
    | select(.focused == true)
    | .fullscreen_mode')

  if [[ "$fullscreen_mode" != "0" ]]; then
    i3-msg fullscreen toggle > /dev/null
    fullscreened=1
  else
    fullscreened=0
  fi
fi

tmux display-popup -d '#{pane_current_path}' -EE -b rounded -S fg="#6c7086" -w 100% -h 99% "$@"

if [ "${fullscreened:-0}" -eq 1 ]; then
  i3-msg fullscreen toggle > /dev/null
fi
