theme = "doom-one"

[editor]
bufferline = "never"
cursorline = false
line-number = "relative"
true-color = true
end-of-line-diagnostics = "hint"
default-yank-register = "+"
continue-comments = false
auto-pairs = false
auto-format = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "▸"
tabpad = "·"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "read-only-indicator", "file-modification-indicator"]
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
V = ["select_mode", "extend_to_line_bounds"]
J = "no_op"

F5 = ":run-shell-command ~/.config/helix/scripts/F5"

[keys.normal.space]
i = ":toggle-option file-picker.git-exclude"

[keys.select]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
J = "no_op"
"C-u" = "page_cursor_half_up"
"C-d" = "page_cursor_half_down"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
