theme = "catppuccin_mocha"

[editor]
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
# Highlight all lines with a cursor
cursorline = true
# Use relative line numbers
line-number = "relative"
# Force the theme to show colors
true-color = true
# Minimum severity to show a diagnostic after the end of a line
end-of-line-diagnostics = "hint"
# Yank and paste using clipboard
default-yank-register = "+"
# Don't add a comment when pressing enter
continue-comments = false
# Don't auto insert {}, "", etc
auto-pairs = false
# Don't auto format on save
auto-format = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "▸"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.file-picker]
# Show hidden files
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "read-only-indicator", "file-modification-indicator"]
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.inline-diagnostics]
cursor-line = "disable" # Don't show inline diagnostics when the cursor is on the line
other-lines = "disable" # Don't expand diagnostics unless the cursor is on the line

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
V = ["select_mode", "extend_to_line_bounds"]
J = "no_op"

F5 = ":run-shell-command ~/.config/helix/scripts/F5"

[keys.normal.space]
i = ":toggle-option file-picker.git-exclude"

[keys.select]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
J = "no_op"
"C-u" = "page_cursor_half_up"
"C-d" = "page_cursor_half_down"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
