#!/usr/bin/env bash

: "${HELIX_F5_CMD:?HELIX_F5_CMD not set}"

tmux split-window -v -l 10 -d "bash -c '
  $HELIX_F5_CMD
  printf \"\nexit code: %d\n\n\" $?
  read -n 1 -s -p \"[press any key to close]\"
'"
